PetShop/Models/Produkt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PetShop.Models
{
    public class Produkt
    {

        public int Id { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Mаксимум 50 карактери ")]
        [Display(Name = "Име :")]
        public string Ime { get; set; }
        [Required]
        [Display(Name = "Наменето за :")]
        public string NamenetoZa { get; set; }
        [Display(Name = "Цена :")]
        public int Cena { get; set; }
        [Display(Name = "Фотографија :")]
        public string ProfilePicture { get; set; }
        public ICollection<Junction> Sopstvenici { get; set; }
    }
}

PetShop/Controllers/ProduktsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetShop.Models;
using PetShop.ViewModels;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace PetShop.Controllers
{
    [Authorize]
    public class ProduktsController : Controller
    {
        private readonly PetShopContext _context;
        private readonly IHostingEnvironment webHostEnvironment;

        public IHostingEnvironment HostEnvironment { get; }

        public ProduktsController(PetShopContext context, IHostingEnvironment hostingEnvironment, IHostingEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Produkts
        public async Task<IActionResult> Index(string produktVid)
        {
            IQueryable<Produkt> produkti = _context.Produkt.AsQueryable();
            IQueryable<string> vidQuery = _context.Produkt.OrderBy(m => m.NamenetoZa).Select(m => m.NamenetoZa).Distinct();
            if (!string.IsNullOrEmpty(produktVid))
            {
                produkti = produkti.Where(x => x.NamenetoZa == produktVid);
            }
            var searchProduktVM = new SearchProduktVM
            {
                Vidovi = new SelectList(await vidQuery.ToListAsync()),
                Produkts = await produkti.ToListAsync()
            };

            return View(searchProduktVM);
        }

        // GET: Produkts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }
        // GET: Produkts/Edit/5
        [Authorize(Policy = "EditProductPolicy")]
        [HttpGet]
        public ViewResult Edit(int id)
        {
            Produkt product = _context.Produkt.FirstOrDefault(c => c.Id == id);
            EditProduktVM produktEditViewModel = new EditProduktVM
            {
                Id = product.Id,
                Ime = product.Ime,
                NamenetoZa = product.NamenetoZa,
                Cena = product.Cena,
                ExistingPhotoPath = product.ProfilePicture
            };
            return View(produktEditViewModel);
        }

        // POST: Produkts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "EditProductPolicy")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditProduktVM model)
        {

            if (ModelState.IsValid)
            {
                Produkt product = _context.Produkt.FirstOrDefault(c => c.Id == model.Id);
                product.Ime = model.Ime;
                product.NamenetoZa = model.NamenetoZa;
                product.Cena = model.Cena;
                if (model.ProfilePicture != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }

                    product.ProfilePicture = UploadedFile(model);
                }

                await _context.SaveChangesAsync(); ;

                return RedirectToAction("index");
            }

            return View(model);
        }

        [Authorize(Policy = "DeleteProductPolicy")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        // POST: Produkts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "DeleteProductPolicy")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produkt = await _context.Produkt.FindAsync(id);
            _context.Produkt.Remove(produkt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduktExists(int id)
        {
            return _context.Produkt.Any(e => e.Id == id);
        }

        // GET: Produkts/Create
        [Authorize(Policy = "CreateProductPolicy")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produkts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "CreateProductPolicy")]
        public async Task<IActionResult> Create(PhotoVM model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(model);
                Produkt produkt = new Produkt
                {
                    Ime = model.Ime,
                    NamenetoZa = model.NamenetoZa,
                    Cena = model.Cena,
                    ProfilePicture = uniqueFileName,

                };


                _context.Add(produkt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        private string UploadedFile(PhotoVM model)
        {
            string uniqueFileName = null;

            if (model.ProfilePicture != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfilePicture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfilePicture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        public IActionResult Poracaj(int id)
        {
            ViewBag.ID =_context.Produkt.Where(m => m.Id==id).Select(p => p.Ime).SingleOrDefault();
            return View();
        }


    }
}

PetShop/Views/Produkts/Create.cshtml
@model PetShop.ViewModels.PhotoVM

@{
    ViewData["Title"] = "Нов Производ";
}

<h2 class="font-weight-bold">Нов производ</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ime" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamenetoZa" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="NamenetoZa" class="form-control" />
                <span asp-validation-for="NamenetoZa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label text-primary font-weight-bolder"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePicture" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Креирај" class="btn btn-outline-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Назад кон листа</a>
</div>

@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
}

PetShop/Views/Produkts/Delete.cshtml
@model PetShop.Models.Produkt

@{
    ViewData["Title"] = "Бриши производ";
    var photoPath = "~/images/" + (Model.ProfilePicture ?? "2.jpg");
}

<h3 class="font-weight-bolder">Дали сте сигурни?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 text-danger">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class="col-sm-10 ">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class="col-sm-2 text-danger">
            @Html.DisplayNameFor(model => model.NamenetoZa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NamenetoZa)
        </dd>
        <dt class="col-sm-2 text-danger">
            @Html.DisplayNameFor(model => model.Cena)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cena)
        </dd>
    </dl>
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Бриши" class="btn btn-outline-secondary" />
    </form>
</div>
<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Назад кон листа</a>
</div>

PetShop/Views/Produkts/Edit.cshtml
@model PetShop.ViewModels.EditProduktVM

@{
    ViewData["Title"] = "Измени производ";
    var photoPath = "~/images/" + (Model.ExistingPhotoPath ?? "2.jpg");
}

<h1>Измени информации: </h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post" class="mt-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamenetoZa" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="NamenetoZa" class="form-control" />
                <span asp-validation-for="NamenetoZa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label text-primary font-weight-bolder"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label text-primary font-weight-bolder"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePicture" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group row col-sm-4 offset-4">
                <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
            </div>
            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-outline-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Назад кон листата</a>
</div>

@section Scripts {
<script type="text/javascript">

        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
</script>
}

PetShop/Views/Produkts/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@model PetShop.ViewModels.SearchProduktVM

@{
    ViewData["Title"] = "Производи";
}
<form asp-controller="Produkts" asp-action="Index" method="get">
    <p>
        <h1 class="text-danger">Наменето за:</h1> <select style="width:170px;height:35px" asp-for="ProduktVid" asp-items="Model.Vidovi">
            <option class="font-weight-bold" value="">All</option>
        </select>
        <input type="submit" value="Филтрирај" class="btn btn-outline-secondary" />
    </p>
</form>

<div class="card-deck">
    @foreach (var item in Model.Produkts)
    {
        var photoPath = "~/images/" + (item.ProfilePicture ?? "2.jpg");
        <div class="card text-white bg-secondary mb-3" style="min-width: 18rem; max-width: 30.5%;">
            <div class="card-header">
                <h3>@item.Ime</h3>
            </div>

            <img class="card-img-top" style="height: 300px;width: auto;" src="@photoPath"
                 asp-append-version="true" />
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-black-50 font-weight-bold">Наменето за : @item.NamenetoZa </li>
                <li class="list-group-item text-black-50 font-weight-bold">Цена : @item.Cena</li>
            </ul>

            <div class="card-footer text-center">
                @if ((await authorizationService.AuthorizeAsync(User, "EditProductPolicy")).Succeeded)
                {
                    <a asp-controller="produkts" asp-action="edit" asp-route-id="@item.Id" class="btn btn-danger m-1">Измени</a>
                }
                @if ((await authorizationService.AuthorizeAsync(User, "DeleteProductPolicy")).Succeeded)
                {
                    <a asp-controller="Produkts" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger m-1">Избриши</a>
                }
                @if (SignInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                {
                <a asp-controller="produkts" asp-action="poracaj" asp-route-id="@item.Id" class="btn btn-danger m-1">Нарачај Производ</a>
                }
            </div>
        </div>
    }
</div>

<div>
    <a class="btn btn-secondary btn-lg btn-block" asp-controller="produkts" asp-action="create">Креирај нов производ</a>
</div>

PetShop/Views/Produkts/Poracaj.cshtml
<div class="text-center">
    <h1>Нарачката на производот <h1 class="text-danger">@ViewBag.ID</h1> <h1>е успешна!</h1>
    <h3>Ви благодариме на довербата.</h3>
</div>